# version: "3.9"
services:

  password_scanner:
    build: ./scanner
    container_name: password_scanner
    volumes:
      - C:/Users/Harsh/Desktop/password-auditor-project-Final/output:/output
# - ./output:/output
    stdin_open: true
    tty: true

  password_viewer:
    build: ./viewer
    container_name: password_viewer
    ports:
      - "8080:80"
    volumes:
      - C:/Users/Harsh/Desktop/password-auditor-project-Final/output:/usr/share/nginx/html
# - ./output:/usr/share/nginx/html
